### ISSUE TITLE
Intelissense (autocomplete) vim

### ISSUE THREAD

**Issue by CarlosEX** [zakuro9715/vim-vtools#1]
Hi, is there any feature you know of with support for intellisense (autocomplete) for vim

**Comment by zakuro9715** [comment]
Autocomplete on language server is planed. It will been implement soon

**Comment by zakuro9715** [comment]
@CarlosEX  Use [vls](https://github.com/vlang/vls) with [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and [asyncomplete-vim](https://github.com/prabirshrestha/asyncomplete.vim)
